name: Test run on PR to dev
'on':
  pull_request:
    branches:
      - dev

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - run: npm run test:unit
